path: .\data\Salinity\processed\by_station-mekong
target: average
date: date
features:
  - station
delimiter: ","
segmentFeature: station
timeFormat:
granularity: 1440 # minutes
fileNameAsFeature: station
hasHeader: True

# %Y: year
# %m: month
# %d: day
# %H: hour
# %M: minute
# %S: second
stripTime:
  # format: "%Y:%m:%d"
  # start:
  #   - 2005
  #   - 2
  #   - 1
  # end:
  #   - 2020
  #   - 4
  #   - 1
